---
- name: first play
  become: true
  remote_user: ec2-user
  become_method: sudo
  hosts: all
  tasks:
    - name: first task to create a user
      user:
        name: maha-ansible
        state: present
