---
- hosts: aap2eda.lab.geekymax.com
  collections:
    - cloud.terraform
  tasks:
    - name: Basic deploy of a service
      cloud.terraform.terraform:
        project_path: '.'
        state: present
